server:
  servlet:
    context-path: /api

spring:
  config:
    import:
      - ./redis-config.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: true